/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./src/**/*.{js,jsx,ts,tsx}'],
    darkMode: 'selector',
    theme: {
        extend: {
            gridTemplateColumns: {
                "13": "repeat(13, minmax(0, 1fr))",
            },
            colors: {
                transparent: "transparent",
                current: "currentColor",
                facebook: "#3b5999",
                twitter: "#55acee",
                dribbble: "#ea4c89",
                pinterest: "#bd081c",
                instagram: "#c32aa3",
            },
            width: {
                "1/7": "14.2857143%",
                "2/7": "28.5714286%",
                "3/7": "42.8571429%",
                "4/7": "57.1428571%",
                "5/7": "71.4285714%",
                "6/7": "85.7142857%",
            },
            scale: {
                "200": "2",
                "250": "2.5",
                "300": "3",
                "350": "3.5",
                "400": "4",
                "500": "5",
            },
            padding: {
                "1/4": "25%",
                "1/3": "33.33%",
                "1/2": "50%",
                "16/9": "56.25%",
                "16/10": "62.5%",
                "2/3": "66.67%",
                "3/4": "75%",
                full: "100%",
            },
            zIndex: {
                "-1": "-1",
                "-10": "-10",
                "-20": "-20",
                "-30": "-30",
                "-40": "-40",
                "-50": "-50",
                "60": "60",
                "70": "70",
                "80": "80",
                "90": "90",
            },
            typography: ({ theme }) => ({
                DEFAULT: {
                    css: {
                        "--tw-prose-body": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-headings": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-lead": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-links": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-bold": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-counters": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-bullets": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-hr": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-quotes": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-quote-borders": theme("colors.primary.DEFAULT"),
                        "--tw-prose-captions": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-code": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-pre-code": theme("colors.white"),
                        "--tw-prose-pre-bg": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-th-borders": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-td-borders": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-invert-body": theme("colors.white"),
                        "--tw-prose-invert-headings": theme("colors.white"),
                        "--tw-prose-invert-lead": theme("colors.white"),
                        "--tw-prose-invert-links": theme("colors.white"),
                        "--tw-prose-invert-bold": theme("colors.white"),
                        "--tw-prose-invert-counters": theme("colors.white"),
                        "--tw-prose-invert-bullets": theme("colors.white"),
                        "--tw-prose-invert-hr": theme("colors.white"),
                        "--tw-prose-invert-quotes": theme("colors.white"),
                        "--tw-prose-invert-quote-borders": theme("colors.white"),
                        "--tw-prose-invert-captions": theme("colors.white"),
                        "--tw-prose-invert-code": theme("colors.white"),
                        "--tw-prose-invert-pre-code": theme("colors.neutral.DEFAULT"),
                        "--tw-prose-invert-pre-bg": theme("colors.white"),
                        "--tw-prose-invert-th-borders": theme("colors.white"),
                        "--tw-prose-invert-td-borders": theme("colors.white"),
                        "ul > li > p, ol > li > p": {
                            marginTop: "0em !important",
                            marginBottom: "0em !important",
                        },
                        ":where(.prose > div > :first-child)": {
                            marginTop: "0 !important",
                        },
                        ":where(.prose > div > :last-child)": {
                            marginBottom: "0 !important",
                        },
                        ".not-prose": {
                            margin: "2rem 0 !important",
                        },
                    },
                },
            }),
            keyframes: {
                shimmer: {
                    "100%": {
                        transform: "translateX(100%)",
                    },
                },
                linspin: {
                    "100%": { transform: "rotate(360deg)" },
                },
                easespin: {
                    "12.5%": { transform: "rotate(135deg)" },
                    "25%": { transform: "rotate(270deg)" },
                    "37.5%": { transform: "rotate(405deg)" },
                    "50%": { transform: "rotate(540deg)" },
                    "62.5%": { transform: "rotate(675deg)" },
                    "75%": { transform: "rotate(810deg)" },
                    "87.5%": { transform: "rotate(945deg)" },
                    "100%": { transform: "rotate(1080deg)" },
                },
                "left-spin": {
                    "0%": { transform: "rotate(130deg)" },
                    "50%": { transform: "rotate(-5deg)" },
                    "100%": { transform: "rotate(130deg)" },
                },
                "right-spin": {
                    "0%": { transform: "rotate(-130deg)" },
                    "50%": { transform: "rotate(5deg)" },
                    "100%": { transform: "rotate(-130deg)" },
                },
                rotating: {
                    "0%, 100%": { transform: "rotate(360deg)" },
                    "50%": { transform: "rotate(0deg)" },
                },
                topbottom: {
                    "0%, 100%": { transform: "translate3d(0, -100%, 0)" },
                    "50%": { transform: "translate3d(0, 0, 0)" },
                },
                bottomtop: {
                    "0%, 100%": { transform: "translate3d(0, 0, 0)" },
                    "50%": { transform: "translate3d(0, -100%, 0)" },
                },
                line: {
                    "0%, 100%": { transform: "translateY(0)" },
                    "50%": { transform: "translateY(100%)" },
                },
                "line-revert": {
                    "0%, 100%": { transform: "translateY(100%)" },
                    "50%": { transform: "translateY(0)" },
                },
            },
            animation: {
                linspin: "linspin 1568.2353ms linear infinite",
                easespin: "easespin 5332ms cubic-bezier(0.4, 0, 0.2, 1) infinite both",
                "left-spin":
                    "left-spin 1333ms cubic-bezier(0.4, 0, 0.2, 1) infinite both",
                "right-spin":
                    "right-spin 1333ms cubic-bezier(0.4, 0, 0.2, 1) infinite both",
                "ping-once": "ping 5s cubic-bezier(0, 0, 0.2, 1)",
                rotating: "rotating 30s linear infinite",
                topbottom: "topbottom 60s infinite alternate linear",
                bottomtop: "bottomtop 60s infinite alternate linear",
                "spin-1.5": "spin 1.5s linear infinite",
                "spin-2": "spin 2s linear infinite",
                "spin-3": "spin 3s linear infinite",
                line1: "line 10s infinite linear",
                line2: "line-revert 8s infinite linear",
                line3: "line 7s infinite linear",
            },
            boxShadow: {
                default: "0px 8px 13px -3px rgba(0, 0, 0, 0.07)",
                card: "0px 1px 3px rgba(0, 0, 0, 0.12)",
                "card-2": "0px 1px 2px rgba(0, 0, 0, 0.05)",
                switcher:
                    "0px 2px 4px rgba(0, 0, 0, 0.2), inset 0px 2px 2px #FFFFFF, inset 0px -1px 1px rgba(0, 0, 0, 0.1)",
                "switch-1": "0px 0px 5px rgba(0, 0, 0, 0.15)",
                1: "0px 1px 3px rgba(0, 0, 0, 0.08)",
                2: "0px 1px 4px rgba(0, 0, 0, 0.12)",
                3: "0px 1px 5px rgba(0, 0, 0, 0.14)",
                4: "0px 4px 10px rgba(0, 0, 0, 0.12)",
                5: "0px 1px 1px rgba(0, 0, 0, 0.15)",
                6: "0px 3px 15px rgba(0, 0, 0, 0.1)",
                7: "-5px 0 0 #313D4A, 5px 0 0 #313D4A",
                8: "1px 0 0 #313D4A, -1px 0 0 #313D4A, 0 1px 0 #313D4A, 0 -1px 0 #313D4A, 0 3px 13px rgb(0 0 0 / 8%)",
                9: "0px 2px 3px rgba(183, 183, 183, 0.5)",
                10: "0px 1px 2px 0px rgba(0, 0, 0, 0.10)",
                11: "0px 1px 3px 0px rgba(166, 175, 195, 0.40)",
                12: "0px 0.5px 3px 0px rgba(0, 0, 0, 0.18)",
                13: "0px 1px 3px 0px rgba(0, 0, 0, 0.08)",
                14: "0px 2px 3px 0px rgba(0, 0, 0, 0.10)",
            },
            dropShadow: {
                1: "0px 1px 0px #E2E8F0",
                2: "0px 1px 4px rgba(0, 0, 0, 0.12)",
                3: "0px 0px 4px rgba(0, 0, 0, 0.15)",
                4: "0px 0px 2px rgba(0, 0, 0, 0.2)",
                5: "0px 1px 5px rgba(0, 0, 0, 0.2)",
            },
        },
    },
    plugins: [
        require("@tailwindcss/typography"),
        require('@tailwindcss/forms'),
        require("@designbycode/tailwindcss-text-shadow"),
    ],
}
